# Generated by Django 4.0.4 on 2022-05-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toppage',
            old_name='featured_image_1',
            new_name='featured_image_bio',
        ),
        migrations.RenameField(
            model_name='toppage',
            old_name='featured_image_2',
            new_name='featured_image_top',
        ),
        migrations.RenameField(
            model_name='toppage',
            old_name='youtube_intro_video_id',
            new_name='youtube_intro_video_embed',
        ),
        migrations.RemoveField(
            model_name='toppage',
            name='name',
        ),
        migrations.AddField(
            model_name='toppage',
            name='firstname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='toppage',
            name='lastname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
