# Generated by Django 4.0.4 on 2022-05-30 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_rename_featured_image_1_toppage_featured_image_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toppage',
            name='freelance',
            field=models.CharField(blank=True, choices=[('unavailable', 'unavailable'), ('available', 'available')], max_length=2000, null=True),
        ),
    ]
