# Generated by Django 4.0.4 on 2022-05-30 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0004_alter_toppage_work_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toppage',
            name='cv_link',
        ),
        migrations.AddField(
            model_name='toppage',
            name='cv_pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='static/files/'),
        ),
        migrations.AlterField(
            model_name='toppage',
            name='work_field',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
