# Generated by Django 4.0.4 on 2022-05-30 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_remove_toppage_cv_link_toppage_cv_pdf_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='color',
            field=models.CharField(blank=True, choices=[('danger', 'red'), ('primary', 'light blue'), ('success', 'green'), ('info', 'blue'), ('warning', 'yellow'), ('dark', 'black'), ('light', 'white')], max_length=2000, null=True),
        ),
    ]
